# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
cache: Carthage
osx_image: xcode9
xcode_sdk: iphonesimulator9.3
env:
  - PLATFORM=iOS
  - PLATFORM=tvOS
  - PLATFORM=Mac
  - PLATFORM=watchOS

before_install:
  - carthage bootstrap --platform $PLATFORM
